name = "Alpaca SMP"
author = "Scott Gould (greysilly7@gmail.com)"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "8046a5194eb63df80277386d19c5b89be7dd843f254c61c7559a846c06b7582d"

[versions]
fabric = "0.14.12"
minecraft = "1.19.3"
