name = "Alpaca SMP"
author = "Scott Gould (greysilly7@gmail.com)"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "03ffa96d2d75040210d112e63b021453d2fd14b7b378453d2574497967eca84f"

[versions]
fabric = "0.14.12"
minecraft = "1.19.3"
